# Generated by Django 4.2.4 on 2023-08-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=200)),
                ('phone', models.IntegerField()),
                ('types', models.CharField(choices=[('IT', 'IT'), ('non IT', 'non IT'), ('Mobile Phone', 'Mobile Phone')], max_length=50)),
                ('activate', models.BooleanField(default=True)),
            ],
        ),
    ]
