# Generated by Django 4.2.4 on 2023-08-24 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('phone_number', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.company')),
            ],
        ),
    ]
