# Generated by Django 4.2.4 on 2023-08-23 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=70)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('about', models.TextField(max_length=500)),
                ('position', models.TextField(choices=[('Manager', 'Manager'), ('Software Developer', 'Software Seveloper'), ('Project Leader', 'Project Leader')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.company')),
            ],
        ),
    ]
