# Generated by Django 4.2.4 on 2023-08-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
